steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image:$SHORT_SHA', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-image:$SHORT_SHA']

  # Authenticate with Google Kubernetes Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'gcp-devops-project', '--zone', 'us-central1-c', '--project', '$PROJECT_ID']

# Deploy to Google Kubernetes Engine using gke-deploy
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: ['run', '--filename', 'gke.yaml', '--image', 'gcr.io/kodekloud-gcp-training/test-gcpdevops:latest', '--location', 'us-central1-c', '--cluster', 'gc', '--namespace', 'gcp-devops-prod']



substitutions:
  _SHORT_SHA: 'unknown'

# Automatically substitute the Git commit SHA as the image tag
options:
  substitution_option: 'ALLOW_LOOSE'

images:
  - 'gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA'

